/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    tenants: Tenant;
    users: User;
    'blog-posts': BlogPost;
    media: Media;
    'github-credentials': GithubCredential;
    'cloudflare-credentials': CloudflareCredential;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    tenants: TenantsSelect<false> | TenantsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'github-credentials': GithubCredentialsSelect<false> | GithubCredentialsSelect<true>;
    'cloudflare-credentials': CloudflareCredentialsSelect<false> | CloudflareCredentialsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'platform-settings': PlatformSetting;
  };
  globalsSelect: {
    'platform-settings': PlatformSettingsSelect<false> | PlatformSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Platform sites (domains, branding, deploy). Only Super Admins can create or edit tenants.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants".
 */
export interface Tenant {
  id: number;
  name: string;
  /**
   * Used as the tenant identifier in URLs, builds, and Wrangler project names. Lowercase letters, digits, and hyphens only — auto-normalized on save.
   */
  slug: string;
  /**
   * Primary domain, e.g. keukenfaqs.nl (no protocol).
   */
  domain: string;
  locale: 'nl-NL' | 'en-GB' | 'en-US' | 'de-DE' | 'fr-FR' | 'es-ES';
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  /**
   * Default Open Graph image (1200×630).
   */
  ogImage?: (number | null) | Media;
  /**
   * Emitted as CSS variables in the tenant site.
   */
  themeTokens?: {
    primary?: string | null;
    primaryDark?: string | null;
    accent?: string | null;
    background?: string | null;
    text?: string | null;
    muted?: string | null;
    fontHeading?: string | null;
    fontBody?: string | null;
    radius?: string | null;
  };
  siteTitle: string;
  siteDescription: string;
  titleSuffix?: string | null;
  robots?: ('index,follow' | 'noindex,follow' | 'noindex,nofollow') | null;
  /**
   * e.g. G-43H5NMZVHK
   */
  ga4Id?: string | null;
  gtmId?: string | null;
  plausibleDomain?: string | null;
  socialLinks?:
    | {
        platform: 'facebook' | 'instagram' | 'twitter' | 'youtube' | 'tiktok' | 'pinterest' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Client site repository: owner/repo or https://github.com/owner/repo. When set, publish deploys from this repo instead of apps/sites/<slug>.
   */
  githubRepo?: string | null;
  /**
   * Branch to checkout for build and setup.
   */
  githubBranch?: string | null;
  /**
   * Optional PAT for this client repo (encrypted). When empty, CI uses EXTERNAL_REPO_GITHUB_TOKEN / GITHUB_TOKEN (legacy).
   */
  githubCredential?: (number | null) | GithubCredential;
  /**
   * CMS modules synced on publish. Only blog is supported today.
   */
  enabledModules?: 'blog'[] | null;
  /**
   * Path inside the Astro repo where blog files are written on publish (e.g. content/blog or src/content/blog).
   */
  blogContentPath?: string | null;
  /**
   * File extension for blog posts synced from Payload on publish. Match your Astro content collection (e.g. MDX sites use .mdx). Import accepts both .md and .mdx.
   */
  blogFileExtension?: ('md' | 'mdx') | null;
  githubSetupStatus?: ('not_connected' | 'validated' | 'setup_dispatched' | 'ready' | 'failed') | null;
  /**
   * Output from the last repository validation.
   */
  githubValidationNotes?: string | null;
  /**
   * Wrangler project name (defaults to slug).
   */
  cloudflareProject?: string | null;
  /**
   * Cloudflare account for Workers deploy (encrypted API token). When empty, uses the Platform credential marked Default, then shared CLOUDFLARE_* CI secrets.
   */
  cloudflareCredential?: (number | null) | CloudflareCredential;
  /**
   * GitHub Actions workflow file used to rebuild this tenant.
   */
  githubWorkflow?: string | null;
  /**
   * Legacy: auto-deploy on every save via webhook. Leave off — editors use Publish content instead.
   */
  webhookEnabled?: boolean | null;
  /**
   * When Publish content was last clicked (CI started).
   */
  lastPublishedAt?: string | null;
  /**
   * When blog markdown was last imported from the connected repo into Payload (also set automatically on first publish if CMS had no posts).
   */
  blogImportedFromRepoAt?: string | null;
  /**
   * Default *.workers.dev URL after deploy. Set automatically by CI; attach your custom domain in Cloudflare separately.
   */
  workersDevUrl?: string | null;
  /**
   * Smoke-test URL before DNS cutover (usually the same as workers.dev until a staging worker exists).
   */
  previewUrl?: string | null;
  lastDeployStatus?: ('idle' | 'dispatched' | 'in_progress' | 'success' | 'failure') | null;
  lastDeployAt?: string | null;
  /**
   * Direct link to the latest GitHub Actions deploy run.
   */
  lastDeployRunUrl?: string | null;
  /**
   * Last deploy failure message (cleared on success).
   */
  lastDeployError?: string | null;
  lastScaffoldStatus?: ('idle' | 'dispatched' | 'in_progress' | 'success' | 'failure') | null;
  lastScaffoldAt?: string | null;
  lastScaffoldRunUrl?: string | null;
  /**
   * Pull request opened by the scaffold workflow.
   */
  lastScaffoldPrUrl?: string | null;
  lastScaffoldError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Images and files for blog posts (hero, featured, SEO). With R2 configured, uploads are stored in your Cloudflare bucket.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  tenant?: (number | null) | Tenant;
  alt?: string | null;
  caption?: string | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    feature?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Encrypted GitHub PATs for external client repositories. Tenants without a credential use platform tokens (EXTERNAL_REPO_GITHUB_TOKEN / GITHUB_TOKEN).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "github-credentials".
 */
export interface GithubCredential {
  id: number;
  /**
   * e.g. "zbseollp production" — shown when linking a tenant.
   */
  label: string;
  /**
   * Optional GitHub user or org (for your notes).
   */
  githubOwner?: string | null;
  token?: string | null;
  /**
   * Last four characters of the stored token.
   */
  tokenLast4?: string | null;
  tokenEncrypted?: string | null;
  /**
   * Scopes, expiry, rotation notes.
   */
  notes?: string | null;
  lastValidatedAt?: string | null;
  lastValidationError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Encrypted Cloudflare API tokens per account. Tenants pick an account for Workers deploy; if unset, the credential marked Default is used.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cloudflare-credentials".
 */
export interface CloudflareCredential {
  id: number;
  /**
   * e.g. "Account A (default)" — shown when linking a tenant.
   */
  label: string;
  /**
   * Cloudflare Account ID (32-char hex from the dashboard URL / Workers overview).
   */
  accountId: string;
  /**
   * Use for tenants with no Cloudflare account selected. Only one credential should be default.
   */
  isDefault?: boolean | null;
  /**
   * Optional workers.dev subdomain for this account (e.g. twilight-breeze-d943). Used when guessing preview URLs.
   */
  workersDevSubdomain?: string | null;
  apiToken?: string | null;
  /**
   * Last four characters of the stored API token.
   */
  apiTokenLast4?: string | null;
  apiTokenEncrypted?: string | null;
  /**
   * Permissions needed: Workers Scripts Edit, Account read. CI falls back to CLOUDFLARE_* env if no credentials exist.
   */
  notes?: string | null;
  lastValidatedAt?: string | null;
  lastValidationError?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Super Admin — create/edit tenants and all sites. Tenant Admin / Editor — assigned sites only (blog & media).
   */
  roles: ('super-admin' | 'tenant-admin' | 'editor')[];
  tenants?:
    | {
        tenant: number | Tenant;
        id?: string | null;
      }[]
    | null;
  totpSecret?: string | null;
  hasTotp?: boolean | null;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  tenant?: (number | null) | Tenant;
  title: string;
  /**
   * URL slug. Auto-normalized: lowercase, hyphens, no special characters.
   */
  slug: string;
  description: string;
  /**
   * Draft = CMS only. Scheduled = CMS only until pub date (hourly cron promotes to Published and deploys). Published = included on live site when Pub date is today or earlier.
   */
  publishStatus: 'draft' | 'scheduled' | 'published';
  /**
   * Display date on the site. Also used as the go-live time for scheduled posts.
   */
  pubDate: string;
  updatedDate?: string | null;
  /**
   * Main post image. Synced as heroImage (and featuredImage when empty) in markdown — R2 CDN URL or local path.
   */
  heroImage?: (number | null) | Media;
  /**
   * Optional card/listing image. Synced as featuredImage in markdown. Falls back to Hero image when empty.
   */
  featuredImage?: (number | null) | Media;
  author?: string | null;
  categories?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Optional custom frontmatter fields for this site (merged into markdown on publish). Use when the connected repo expects extra keys.
   */
  extra?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Per-page SEO overrides. Falls back to the tenant defaults when blank.
   */
  seo?: {
    title?: string | null;
    description?: string | null;
    ogImage?: (number | null) | Media;
    /**
     * e.g. noindex,follow
     */
    robots?: string | null;
    /**
     * Override canonical URL if different from this site.
     */
    canonicalUrl?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'tenants';
        value: number | Tenant;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'github-credentials';
        value: number | GithubCredential;
      } | null)
    | ({
        relationTo: 'cloudflare-credentials';
        value: number | CloudflareCredential;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tenants_select".
 */
export interface TenantsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  locale?: T;
  logo?: T;
  favicon?: T;
  ogImage?: T;
  themeTokens?:
    | T
    | {
        primary?: T;
        primaryDark?: T;
        accent?: T;
        background?: T;
        text?: T;
        muted?: T;
        fontHeading?: T;
        fontBody?: T;
        radius?: T;
      };
  siteTitle?: T;
  siteDescription?: T;
  titleSuffix?: T;
  robots?: T;
  ga4Id?: T;
  gtmId?: T;
  plausibleDomain?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  githubRepo?: T;
  githubBranch?: T;
  githubCredential?: T;
  enabledModules?: T;
  blogContentPath?: T;
  blogFileExtension?: T;
  githubSetupStatus?: T;
  githubValidationNotes?: T;
  cloudflareProject?: T;
  cloudflareCredential?: T;
  githubWorkflow?: T;
  webhookEnabled?: T;
  lastPublishedAt?: T;
  blogImportedFromRepoAt?: T;
  workersDevUrl?: T;
  previewUrl?: T;
  lastDeployStatus?: T;
  lastDeployAt?: T;
  lastDeployRunUrl?: T;
  lastDeployError?: T;
  lastScaffoldStatus?: T;
  lastScaffoldAt?: T;
  lastScaffoldRunUrl?: T;
  lastScaffoldPrUrl?: T;
  lastScaffoldError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  totpSecret?: T;
  hasTotp?: T;
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  slug?: T;
  description?: T;
  publishStatus?: T;
  pubDate?: T;
  updatedDate?: T;
  heroImage?: T;
  featuredImage?: T;
  author?: T;
  categories?:
    | T
    | {
        value?: T;
        id?: T;
      };
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  content?: T;
  extra?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
        robots?: T;
        canonicalUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  caption?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        feature?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "github-credentials_select".
 */
export interface GithubCredentialsSelect<T extends boolean = true> {
  label?: T;
  githubOwner?: T;
  token?: T;
  tokenLast4?: T;
  tokenEncrypted?: T;
  notes?: T;
  lastValidatedAt?: T;
  lastValidationError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cloudflare-credentials_select".
 */
export interface CloudflareCredentialsSelect<T extends boolean = true> {
  label?: T;
  accountId?: T;
  isDefault?: T;
  workersDevSubdomain?: T;
  apiToken?: T;
  apiTokenLast4?: T;
  apiTokenEncrypted?: T;
  notes?: T;
  lastValidatedAt?: T;
  lastValidationError?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * CI/CD and platform defaults. Only super-admins can edit.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-settings".
 */
export interface PlatformSetting {
  id: number;
  /**
   * Where tenant pipelines run (deploy, import, scaffold, setup, scheduled publish). Jenkins requires JENKINS_URL, JENKINS_USER, JENKINS_API_TOKEN in server .env.
   */
  ciProvider: 'github_actions' | 'jenkins';
  /**
   * Jenkins job names are configured via server env (JENKINS_JOB_DEPLOY, etc.). See jenkins/README.md.
   */
  jenkinsNotes?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "platform-settings_select".
 */
export interface PlatformSettingsSelect<T extends boolean = true> {
  ciProvider?: T;
  jenkinsNotes?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}